#!/usr/bin/env python3

import json
import sys
from wiki_inputs import *

arg1 = get(1)

try:
    val=eval("""{{text|escapejs}}
""")
except SyntaxError as e:
    msg = {'type': 'error', 'val': f"line {e.lineno:2d}:{e.text}\n" + " " * (8+e.offset) + "^"}
    print(f"#WI_NATIVE {json.dumps(msg)}")
    sys.exit()
except TypeError as e:
    val = None
except Exception as e:
    print("#WI_NATIVE " + json.dumps({"type": "error", "val":f"error: {e!s}"}))
    sys.exit()

if val is None:
    print("#WI_NATIVE " + json.dumps({"type": None}))
elif val.__class__.__name__ in ['str', 'int', 'float']:
    print("#WI_NATIVE " + json.dumps({"type": val.__class__.__name__, 'val': val}))

else:
    print("#WI_NATIVE " + json.dumps({"type": 'error', 'val': val.__class__.__name__ + ":" + str(val)}))
