# Generated by Django 2.1 on 2018-08-30 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wiki', '0002_urlpath_moved_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=28)),
                ('created', models.DateTimeField()),
                ('val', models.TextField(blank=True, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.Article', verbose_name='article')),
                ('author', models.ForeignKey(blank=True, help_text='the author of the input.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='input_author', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(help_text='the owner of the input.', on_delete=django.db.models.deletion.CASCADE, related_name='input_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Input',
                'verbose_name_plural': 'Inputs',
                'ordering': ['article', 'name', 'owner', 'created'],
                'get_latest_by': ['article', 'name', 'owner', 'created'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='input',
            unique_together={('article', 'name', 'owner', 'created')},
        ),
    ]
